name: 'xcresult-summary'
description: 'Generate a markdown summary from Xcode test results (.xcresult)'
author: 'tsoejima'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  xcresult-path:
    description: 'Path to the .xcresult bundle'
    required: true
    default: 'build/reports/tests.xcresult'

outputs:
  summary:
    description: 'Test summary in markdown format'
  total-tests:
    description: 'Total number of tests'
  failed-tests:
    description: 'Number of failed tests'
  passed-tests:
    description: 'Number of passed tests'
  build-status:
    description: 'Build status (succeeded/failed)'
  error-count:
    description: 'Number of build errors'
  warning-count:
    description: 'Number of build warnings'

runs:
  using: 'node20'
  main: 'dist/index.js'
